/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ISlashPool {
    function stakeOf(address operator) external view returns (uint256);

    function beneficiaryBalanceOf(address beneficiary) external view returns (uint256);

    function proofUsed(bytes32 proof_hash) external view returns (bool);

    function deposit(address operator, uint256 amount) external returns (bool);

    function submitViolation(address operator, address beneficiary, uint256 amount, bytes32 proof_hash) external returns (bool);
}
