[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
ffi = false
fs_permissions = [{ access = "read-write", path = "./" }]

remappings = [
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "forge-std/=node_modules/forge-std/src/"
]
